version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile



  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword  #TODO: - move to secrets file
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - log-volume:/logs 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
    volumes:
      - seq-data:/data 


volumes:
    log-volume:
    pg-data:
    seq-data: